### ISSUE TITLE
Feature request: Hotloading of proposed answers

### ISSUE THREAD

**Issue by MathiasSchindler** [okfde/eucopyright#1]
A number of organisations are going to provide suggestions how an appropriate answer might look like. This feature request proposes a tool to load the form with those proposed by such organisations. A user might chose to hotload answers and then customize it or alter certain answers she/he disagrees with. In the interest of plurality, more than one organisation should be able to provide those lists of suggested answers.

**Comment by stefanw** [comment]
Implemented in b3f8638754d756d2b4a62a8525ecc8d7893ca3e7.
