### ISSUE TITLE
Get a proper domain name?

### ISSUE THREAD

**Issue by stefanw** [okfde/eucopyright#10]
Should we? Any ideas?

**Comment by MathiasSchindler** [comment]
Something like copyright-reform.eu (free) or copyright-consultation.eu / .info

**Comment by stefanw** [comment]
A subdomain of http://fixcopyright.eu/ is also in the discussion. Something like consultation.fixcopyright.eu

**Comment by PeterTheOne** [comment]
copywrongs.eu is registered by @c3o, see: https://twitter.com/c3o/status/417708097054838784

**Comment by stefanw** [comment]
The domain will now be http://youcan.fixcopyright.eu, will make the switch later tonight.
