### ISSUE TITLE
Set public launch date with deadline for data from organisations

### ISSUE THREAD

**Issue by stefanw** [okfde/eucopyright#11]
Launch tasks:
- [ ] Remove beta status
- [ ] Remove example organisation
- [ ] Move organisation guides as CSV into repo

**Comment by PeterTheOne** [comment]
What organisations are we waiting for? And what other organisations could we contact?

**Comment by stefanw** [comment]
I'm waiting for feedback from [Copyright for Creativity](http://copyright4creativity.eu/).

**Comment by stefanw** [comment]
Since all launch tasks are basically complete, I'm closing this.
The site is practically launched. Promotion coordination is not part of this repository.
