### ISSUE TITLE
Feature request: Export of Form into ready-to-submit PDF/ODT file

### ISSUE THREAD

**Issue by MathiasSchindler** [okfde/eucopyright#2]
The answered form should be support export as a decent-formatted PDF/ODT for submission to the European commission

**Comment by stefanw** [comment]
There is an export to ODT already generated in JavaScript. PDF generation will probably need a server which would require additional resources. Advantage of the ODT is that it's open and you can edit it after downloading.

**Comment by PeterTheOne** [comment]
As discussed at the 30c3, the EU has to accept open formats.

**Comment by stefanw** [comment]
ODT-File is only option now. Don't see an easy way to produce a PDF.
