### ISSUE TITLE
Download doesn't work with safari browser on iOS

### ISSUE THREAD

**Issue by PeterTheOne** [okfde/eucopyright#26]

**Comment by stefanw** [comment]
I noticed this as well. Even though blob URL are supported in Mobile Safari, there is no download feature.

I'm working on a feature that allows you to enter an email address and get the document send to you so you can forward it.

The following cases needs to be covered:
- JavaScript is off
- Browser does not support Blob URL
- Browser does not support Flash

I'm working on the most severe case of JavaScript is off right now and will provide a backup solution.

**Comment by stefanw** [comment]
We now have the possibility to do the following:
- generate document in browser and download it to the user
- generate the document on the server, optionally email it and download it to the user OR redirect to a page

We need some solid JS code that detects what the current browser support and what the best course of action would be.

**Comment by PeterTheOne** [comment]
Can http://modernizr.com/ do the detection part?

**Comment by stefanw** [comment]
I simply dropped the client-side generation for now, form works now without JS. Server-side does generation of document and email sending. Download is also possible by leaving out the `redirect` parameter of the service.

Feel free to port 30c3 to the new backend. You can also send the form data with `$.serialize` and for email sending if you want.
