### ISSUE TITLE
No pre-selection of "Type of respondent"

### ISSUE THREAD

**Issue by MathiasSchindler** [okfde/eucopyright#6]
As of now, "End user/consumer" is the pre-selected type of respondent. There should be made no such assumption. Selecting (at least) one should be mandatory. The original EU commission form appears to be multiple choice for type of respondent.

**Comment by stefanw** [comment]
Can you select multiple? I would think this as a valid option, but would like feedback.

**Comment by stefanw** [comment]
Removed the default state in a3f932feff540468c33e9ed30aba587677ecb4e2. Still the question, if multiple can be selected.

**Comment by stefanw** [comment]
This is now a multi-select, pre-select on persona site.
