### ISSUE TITLE
Finish Wikimedia answers in spreadsheet

### ISSUE THREAD

**Issue by stefanw** [okfde/eucopyright#7]
Possibly with explanation why the question was answered that way.

**Comment by MathiasSchindler** [comment]
Timeline for completion of the answers is December 17 for a first draft of the final answers and finalization after that.

**Comment by PeterTheOne** [comment]
@MathiasSchindler What is the status of the Wikimedia answers?

**Comment by stefanw** [comment]
@MathiasSchindler I removed the Wikimedia answers for now as they are incomplete.

**Comment by MathiasSchindler** [comment]
The incompleteness has gone.

**Comment by MathiasSchindler** [comment]
The answers should indeed be labeled as Wikimedia.

**Comment by stefanw** [comment]
Would it make sense to move the answer colum to the explanation column? Prefilled answers are apparently not the way to go.

The spreadsheet also requires option values for multiple choice answers.

**Comment by stefanw** [comment]
I reintegrated the answers. Any chance to get the answers also in German [for the German site](http://youcan.fixcopyright.eu/de/)?

**Comment by stefanw** [comment]
Wikimedia is back in, would welcome a German translation of the guide if at all possible. Closing this now.
